spring.application.name=foro_hub
spring.datasource.url=jdbc:postgresql://localhost/forohub_bd
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:alura-latam-one-g9}
jwt.expiration=2
jwt.issuer=foro-hub-api